/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaDisenoRouteImport } from './routes/sistema-diseno'
import { Route as IndexRouteImport } from './routes/index'

const SistemaDisenoRoute = SistemaDisenoRouteImport.update({
  id: '/sistema-diseno',
  path: '/sistema-diseno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sistema-diseno': typeof SistemaDisenoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sistema-diseno': typeof SistemaDisenoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sistema-diseno': typeof SistemaDisenoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sistema-diseno'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sistema-diseno'
  id: '__root__' | '/' | '/sistema-diseno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SistemaDisenoRoute: typeof SistemaDisenoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema-diseno': {
      id: '/sistema-diseno'
      path: '/sistema-diseno'
      fullPath: '/sistema-diseno'
      preLoaderRoute: typeof SistemaDisenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SistemaDisenoRoute: SistemaDisenoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
