/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetupRouteRouteImport } from './routes/_authenticated/setup/route'
import { Route as AuthenticatedPgciRouteRouteImport } from './routes/_authenticated/pgci/route'
import { Route as AuthenticatedSetupIndexRouteImport } from './routes/_authenticated/setup/index'
import { Route as AuthenticatedPgciIndexRouteImport } from './routes/_authenticated/pgci/index'
import { Route as AuthenticatedSetupUsersIndexRouteImport } from './routes/_authenticated/setup/users.index'
import { Route as AuthenticatedSetupProductsIndexRouteImport } from './routes/_authenticated/setup/products.index'
import { Route as AuthenticatedSetupClientsIndexRouteImport } from './routes/_authenticated/setup/clients.index'
import { Route as AuthenticatedPgciAgreementsIndexRouteImport } from './routes/_authenticated/pgci/agreements.index'
import { Route as AuthenticatedSetupUsersNewRouteImport } from './routes/_authenticated/setup/users.new'
import { Route as AuthenticatedSetupUsersUserIdRouteImport } from './routes/_authenticated/setup/users.$userId'
import { Route as AuthenticatedSetupProductsImportRouteImport } from './routes/_authenticated/setup/products.import'
import { Route as AuthenticatedSetupProductsProductIdRouteImport } from './routes/_authenticated/setup/products.$productId'
import { Route as AuthenticatedSetupClientsNewRouteImport } from './routes/_authenticated/setup/clients.new'
import { Route as AuthenticatedSetupClientsClientIdRouteImport } from './routes/_authenticated/setup/clients.$clientId'
import { Route as AuthenticatedPgciAgreementsNewRouteImport } from './routes/_authenticated/pgci/agreements.new'
import { Route as AuthenticatedSetupUsersUserIdIndexRouteImport } from './routes/_authenticated/setup/users.$userId.index'
import { Route as AuthenticatedSetupClientsClientIdIndexRouteImport } from './routes/_authenticated/setup/clients.$clientId.index'
import { Route as AuthenticatedPgciAgreementsAgreementIdIndexRouteImport } from './routes/_authenticated/pgci/agreements.$agreementId.index'
import { Route as AuthenticatedSetupUsersUserIdEditRouteImport } from './routes/_authenticated/setup/users.$userId.edit'
import { Route as AuthenticatedSetupUsersUserIdClientAccessRouteImport } from './routes/_authenticated/setup/users.$userId.client-access'
import { Route as AuthenticatedSetupClientsClientIdEditRouteImport } from './routes/_authenticated/setup/clients.$clientId.edit'
import { Route as AuthenticatedSetupClientsClientIdCompaniesRouteImport } from './routes/_authenticated/setup/clients.$clientId.companies'
import { Route as AuthenticatedPgciAgreementsAgreementIdEditRouteImport } from './routes/_authenticated/pgci/agreements.$agreementId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRouteRoute = AuthenticatedSetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPgciRouteRoute = AuthenticatedPgciRouteRouteImport.update({
  id: '/pgci',
  path: '/pgci',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupIndexRoute = AuthenticatedSetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSetupRouteRoute,
} as any)
const AuthenticatedPgciIndexRoute = AuthenticatedPgciIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPgciRouteRoute,
} as any)
const AuthenticatedSetupUsersIndexRoute =
  AuthenticatedSetupUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupProductsIndexRoute =
  AuthenticatedSetupProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupClientsIndexRoute =
  AuthenticatedSetupClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedPgciAgreementsIndexRoute =
  AuthenticatedPgciAgreementsIndexRouteImport.update({
    id: '/agreements/',
    path: '/agreements/',
    getParentRoute: () => AuthenticatedPgciRouteRoute,
  } as any)
const AuthenticatedSetupUsersNewRoute =
  AuthenticatedSetupUsersNewRouteImport.update({
    id: '/users/new',
    path: '/users/new',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupUsersUserIdRoute =
  AuthenticatedSetupUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupProductsImportRoute =
  AuthenticatedSetupProductsImportRouteImport.update({
    id: '/products/import',
    path: '/products/import',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupProductsProductIdRoute =
  AuthenticatedSetupProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupClientsNewRoute =
  AuthenticatedSetupClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedSetupClientsClientIdRoute =
  AuthenticatedSetupClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedSetupRouteRoute,
  } as any)
const AuthenticatedPgciAgreementsNewRoute =
  AuthenticatedPgciAgreementsNewRouteImport.update({
    id: '/agreements/new',
    path: '/agreements/new',
    getParentRoute: () => AuthenticatedPgciRouteRoute,
  } as any)
const AuthenticatedSetupUsersUserIdIndexRoute =
  AuthenticatedSetupUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSetupUsersUserIdRoute,
  } as any)
const AuthenticatedSetupClientsClientIdIndexRoute =
  AuthenticatedSetupClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSetupClientsClientIdRoute,
  } as any)
const AuthenticatedPgciAgreementsAgreementIdIndexRoute =
  AuthenticatedPgciAgreementsAgreementIdIndexRouteImport.update({
    id: '/agreements/$agreementId/',
    path: '/agreements/$agreementId/',
    getParentRoute: () => AuthenticatedPgciRouteRoute,
  } as any)
const AuthenticatedSetupUsersUserIdEditRoute =
  AuthenticatedSetupUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSetupUsersUserIdRoute,
  } as any)
const AuthenticatedSetupUsersUserIdClientAccessRoute =
  AuthenticatedSetupUsersUserIdClientAccessRouteImport.update({
    id: '/client-access',
    path: '/client-access',
    getParentRoute: () => AuthenticatedSetupUsersUserIdRoute,
  } as any)
const AuthenticatedSetupClientsClientIdEditRoute =
  AuthenticatedSetupClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSetupClientsClientIdRoute,
  } as any)
const AuthenticatedSetupClientsClientIdCompaniesRoute =
  AuthenticatedSetupClientsClientIdCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedSetupClientsClientIdRoute,
  } as any)
const AuthenticatedPgciAgreementsAgreementIdEditRoute =
  AuthenticatedPgciAgreementsAgreementIdEditRouteImport.update({
    id: '/agreements/$agreementId/edit',
    path: '/agreements/$agreementId/edit',
    getParentRoute: () => AuthenticatedPgciRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pgci': typeof AuthenticatedPgciRouteRouteWithChildren
  '/setup': typeof AuthenticatedSetupRouteRouteWithChildren
  '/pgci/': typeof AuthenticatedPgciIndexRoute
  '/setup/': typeof AuthenticatedSetupIndexRoute
  '/pgci/agreements/new': typeof AuthenticatedPgciAgreementsNewRoute
  '/setup/clients/$clientId': typeof AuthenticatedSetupClientsClientIdRouteWithChildren
  '/setup/clients/new': typeof AuthenticatedSetupClientsNewRoute
  '/setup/products/$productId': typeof AuthenticatedSetupProductsProductIdRoute
  '/setup/products/import': typeof AuthenticatedSetupProductsImportRoute
  '/setup/users/$userId': typeof AuthenticatedSetupUsersUserIdRouteWithChildren
  '/setup/users/new': typeof AuthenticatedSetupUsersNewRoute
  '/pgci/agreements/': typeof AuthenticatedPgciAgreementsIndexRoute
  '/setup/clients/': typeof AuthenticatedSetupClientsIndexRoute
  '/setup/products/': typeof AuthenticatedSetupProductsIndexRoute
  '/setup/users/': typeof AuthenticatedSetupUsersIndexRoute
  '/pgci/agreements/$agreementId/edit': typeof AuthenticatedPgciAgreementsAgreementIdEditRoute
  '/setup/clients/$clientId/companies': typeof AuthenticatedSetupClientsClientIdCompaniesRoute
  '/setup/clients/$clientId/edit': typeof AuthenticatedSetupClientsClientIdEditRoute
  '/setup/users/$userId/client-access': typeof AuthenticatedSetupUsersUserIdClientAccessRoute
  '/setup/users/$userId/edit': typeof AuthenticatedSetupUsersUserIdEditRoute
  '/pgci/agreements/$agreementId/': typeof AuthenticatedPgciAgreementsAgreementIdIndexRoute
  '/setup/clients/$clientId/': typeof AuthenticatedSetupClientsClientIdIndexRoute
  '/setup/users/$userId/': typeof AuthenticatedSetupUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pgci': typeof AuthenticatedPgciIndexRoute
  '/setup': typeof AuthenticatedSetupIndexRoute
  '/pgci/agreements/new': typeof AuthenticatedPgciAgreementsNewRoute
  '/setup/clients/new': typeof AuthenticatedSetupClientsNewRoute
  '/setup/products/$productId': typeof AuthenticatedSetupProductsProductIdRoute
  '/setup/products/import': typeof AuthenticatedSetupProductsImportRoute
  '/setup/users/new': typeof AuthenticatedSetupUsersNewRoute
  '/pgci/agreements': typeof AuthenticatedPgciAgreementsIndexRoute
  '/setup/clients': typeof AuthenticatedSetupClientsIndexRoute
  '/setup/products': typeof AuthenticatedSetupProductsIndexRoute
  '/setup/users': typeof AuthenticatedSetupUsersIndexRoute
  '/pgci/agreements/$agreementId/edit': typeof AuthenticatedPgciAgreementsAgreementIdEditRoute
  '/setup/clients/$clientId/companies': typeof AuthenticatedSetupClientsClientIdCompaniesRoute
  '/setup/clients/$clientId/edit': typeof AuthenticatedSetupClientsClientIdEditRoute
  '/setup/users/$userId/client-access': typeof AuthenticatedSetupUsersUserIdClientAccessRoute
  '/setup/users/$userId/edit': typeof AuthenticatedSetupUsersUserIdEditRoute
  '/pgci/agreements/$agreementId': typeof AuthenticatedPgciAgreementsAgreementIdIndexRoute
  '/setup/clients/$clientId': typeof AuthenticatedSetupClientsClientIdIndexRoute
  '/setup/users/$userId': typeof AuthenticatedSetupUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/pgci': typeof AuthenticatedPgciRouteRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRouteRouteWithChildren
  '/_authenticated/pgci/': typeof AuthenticatedPgciIndexRoute
  '/_authenticated/setup/': typeof AuthenticatedSetupIndexRoute
  '/_authenticated/pgci/agreements/new': typeof AuthenticatedPgciAgreementsNewRoute
  '/_authenticated/setup/clients/$clientId': typeof AuthenticatedSetupClientsClientIdRouteWithChildren
  '/_authenticated/setup/clients/new': typeof AuthenticatedSetupClientsNewRoute
  '/_authenticated/setup/products/$productId': typeof AuthenticatedSetupProductsProductIdRoute
  '/_authenticated/setup/products/import': typeof AuthenticatedSetupProductsImportRoute
  '/_authenticated/setup/users/$userId': typeof AuthenticatedSetupUsersUserIdRouteWithChildren
  '/_authenticated/setup/users/new': typeof AuthenticatedSetupUsersNewRoute
  '/_authenticated/pgci/agreements/': typeof AuthenticatedPgciAgreementsIndexRoute
  '/_authenticated/setup/clients/': typeof AuthenticatedSetupClientsIndexRoute
  '/_authenticated/setup/products/': typeof AuthenticatedSetupProductsIndexRoute
  '/_authenticated/setup/users/': typeof AuthenticatedSetupUsersIndexRoute
  '/_authenticated/pgci/agreements/$agreementId/edit': typeof AuthenticatedPgciAgreementsAgreementIdEditRoute
  '/_authenticated/setup/clients/$clientId/companies': typeof AuthenticatedSetupClientsClientIdCompaniesRoute
  '/_authenticated/setup/clients/$clientId/edit': typeof AuthenticatedSetupClientsClientIdEditRoute
  '/_authenticated/setup/users/$userId/client-access': typeof AuthenticatedSetupUsersUserIdClientAccessRoute
  '/_authenticated/setup/users/$userId/edit': typeof AuthenticatedSetupUsersUserIdEditRoute
  '/_authenticated/pgci/agreements/$agreementId/': typeof AuthenticatedPgciAgreementsAgreementIdIndexRoute
  '/_authenticated/setup/clients/$clientId/': typeof AuthenticatedSetupClientsClientIdIndexRoute
  '/_authenticated/setup/users/$userId/': typeof AuthenticatedSetupUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pgci'
    | '/setup'
    | '/pgci/'
    | '/setup/'
    | '/pgci/agreements/new'
    | '/setup/clients/$clientId'
    | '/setup/clients/new'
    | '/setup/products/$productId'
    | '/setup/products/import'
    | '/setup/users/$userId'
    | '/setup/users/new'
    | '/pgci/agreements/'
    | '/setup/clients/'
    | '/setup/products/'
    | '/setup/users/'
    | '/pgci/agreements/$agreementId/edit'
    | '/setup/clients/$clientId/companies'
    | '/setup/clients/$clientId/edit'
    | '/setup/users/$userId/client-access'
    | '/setup/users/$userId/edit'
    | '/pgci/agreements/$agreementId/'
    | '/setup/clients/$clientId/'
    | '/setup/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pgci'
    | '/setup'
    | '/pgci/agreements/new'
    | '/setup/clients/new'
    | '/setup/products/$productId'
    | '/setup/products/import'
    | '/setup/users/new'
    | '/pgci/agreements'
    | '/setup/clients'
    | '/setup/products'
    | '/setup/users'
    | '/pgci/agreements/$agreementId/edit'
    | '/setup/clients/$clientId/companies'
    | '/setup/clients/$clientId/edit'
    | '/setup/users/$userId/client-access'
    | '/setup/users/$userId/edit'
    | '/pgci/agreements/$agreementId'
    | '/setup/clients/$clientId'
    | '/setup/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/pgci'
    | '/_authenticated/setup'
    | '/_authenticated/pgci/'
    | '/_authenticated/setup/'
    | '/_authenticated/pgci/agreements/new'
    | '/_authenticated/setup/clients/$clientId'
    | '/_authenticated/setup/clients/new'
    | '/_authenticated/setup/products/$productId'
    | '/_authenticated/setup/products/import'
    | '/_authenticated/setup/users/$userId'
    | '/_authenticated/setup/users/new'
    | '/_authenticated/pgci/agreements/'
    | '/_authenticated/setup/clients/'
    | '/_authenticated/setup/products/'
    | '/_authenticated/setup/users/'
    | '/_authenticated/pgci/agreements/$agreementId/edit'
    | '/_authenticated/setup/clients/$clientId/companies'
    | '/_authenticated/setup/clients/$clientId/edit'
    | '/_authenticated/setup/users/$userId/client-access'
    | '/_authenticated/setup/users/$userId/edit'
    | '/_authenticated/pgci/agreements/$agreementId/'
    | '/_authenticated/setup/clients/$clientId/'
    | '/_authenticated/setup/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pgci': {
      id: '/_authenticated/pgci'
      path: '/pgci'
      fullPath: '/pgci'
      preLoaderRoute: typeof AuthenticatedPgciRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/': {
      id: '/_authenticated/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof AuthenticatedSetupIndexRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/pgci/': {
      id: '/_authenticated/pgci/'
      path: '/'
      fullPath: '/pgci/'
      preLoaderRoute: typeof AuthenticatedPgciIndexRouteImport
      parentRoute: typeof AuthenticatedPgciRouteRoute
    }
    '/_authenticated/setup/users/': {
      id: '/_authenticated/setup/users/'
      path: '/users'
      fullPath: '/setup/users/'
      preLoaderRoute: typeof AuthenticatedSetupUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/products/': {
      id: '/_authenticated/setup/products/'
      path: '/products'
      fullPath: '/setup/products/'
      preLoaderRoute: typeof AuthenticatedSetupProductsIndexRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/clients/': {
      id: '/_authenticated/setup/clients/'
      path: '/clients'
      fullPath: '/setup/clients/'
      preLoaderRoute: typeof AuthenticatedSetupClientsIndexRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/pgci/agreements/': {
      id: '/_authenticated/pgci/agreements/'
      path: '/agreements'
      fullPath: '/pgci/agreements/'
      preLoaderRoute: typeof AuthenticatedPgciAgreementsIndexRouteImport
      parentRoute: typeof AuthenticatedPgciRouteRoute
    }
    '/_authenticated/setup/users/new': {
      id: '/_authenticated/setup/users/new'
      path: '/users/new'
      fullPath: '/setup/users/new'
      preLoaderRoute: typeof AuthenticatedSetupUsersNewRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/users/$userId': {
      id: '/_authenticated/setup/users/$userId'
      path: '/users/$userId'
      fullPath: '/setup/users/$userId'
      preLoaderRoute: typeof AuthenticatedSetupUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/products/import': {
      id: '/_authenticated/setup/products/import'
      path: '/products/import'
      fullPath: '/setup/products/import'
      preLoaderRoute: typeof AuthenticatedSetupProductsImportRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/products/$productId': {
      id: '/_authenticated/setup/products/$productId'
      path: '/products/$productId'
      fullPath: '/setup/products/$productId'
      preLoaderRoute: typeof AuthenticatedSetupProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/clients/new': {
      id: '/_authenticated/setup/clients/new'
      path: '/clients/new'
      fullPath: '/setup/clients/new'
      preLoaderRoute: typeof AuthenticatedSetupClientsNewRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/setup/clients/$clientId': {
      id: '/_authenticated/setup/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/setup/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedSetupClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedSetupRouteRoute
    }
    '/_authenticated/pgci/agreements/new': {
      id: '/_authenticated/pgci/agreements/new'
      path: '/agreements/new'
      fullPath: '/pgci/agreements/new'
      preLoaderRoute: typeof AuthenticatedPgciAgreementsNewRouteImport
      parentRoute: typeof AuthenticatedPgciRouteRoute
    }
    '/_authenticated/setup/users/$userId/': {
      id: '/_authenticated/setup/users/$userId/'
      path: '/'
      fullPath: '/setup/users/$userId/'
      preLoaderRoute: typeof AuthenticatedSetupUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedSetupUsersUserIdRoute
    }
    '/_authenticated/setup/clients/$clientId/': {
      id: '/_authenticated/setup/clients/$clientId/'
      path: '/'
      fullPath: '/setup/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedSetupClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedSetupClientsClientIdRoute
    }
    '/_authenticated/pgci/agreements/$agreementId/': {
      id: '/_authenticated/pgci/agreements/$agreementId/'
      path: '/agreements/$agreementId'
      fullPath: '/pgci/agreements/$agreementId/'
      preLoaderRoute: typeof AuthenticatedPgciAgreementsAgreementIdIndexRouteImport
      parentRoute: typeof AuthenticatedPgciRouteRoute
    }
    '/_authenticated/setup/users/$userId/edit': {
      id: '/_authenticated/setup/users/$userId/edit'
      path: '/edit'
      fullPath: '/setup/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedSetupUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedSetupUsersUserIdRoute
    }
    '/_authenticated/setup/users/$userId/client-access': {
      id: '/_authenticated/setup/users/$userId/client-access'
      path: '/client-access'
      fullPath: '/setup/users/$userId/client-access'
      preLoaderRoute: typeof AuthenticatedSetupUsersUserIdClientAccessRouteImport
      parentRoute: typeof AuthenticatedSetupUsersUserIdRoute
    }
    '/_authenticated/setup/clients/$clientId/edit': {
      id: '/_authenticated/setup/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/setup/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedSetupClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedSetupClientsClientIdRoute
    }
    '/_authenticated/setup/clients/$clientId/companies': {
      id: '/_authenticated/setup/clients/$clientId/companies'
      path: '/companies'
      fullPath: '/setup/clients/$clientId/companies'
      preLoaderRoute: typeof AuthenticatedSetupClientsClientIdCompaniesRouteImport
      parentRoute: typeof AuthenticatedSetupClientsClientIdRoute
    }
    '/_authenticated/pgci/agreements/$agreementId/edit': {
      id: '/_authenticated/pgci/agreements/$agreementId/edit'
      path: '/agreements/$agreementId/edit'
      fullPath: '/pgci/agreements/$agreementId/edit'
      preLoaderRoute: typeof AuthenticatedPgciAgreementsAgreementIdEditRouteImport
      parentRoute: typeof AuthenticatedPgciRouteRoute
    }
  }
}

interface AuthenticatedPgciRouteRouteChildren {
  AuthenticatedPgciIndexRoute: typeof AuthenticatedPgciIndexRoute
  AuthenticatedPgciAgreementsNewRoute: typeof AuthenticatedPgciAgreementsNewRoute
  AuthenticatedPgciAgreementsIndexRoute: typeof AuthenticatedPgciAgreementsIndexRoute
  AuthenticatedPgciAgreementsAgreementIdEditRoute: typeof AuthenticatedPgciAgreementsAgreementIdEditRoute
  AuthenticatedPgciAgreementsAgreementIdIndexRoute: typeof AuthenticatedPgciAgreementsAgreementIdIndexRoute
}

const AuthenticatedPgciRouteRouteChildren: AuthenticatedPgciRouteRouteChildren =
  {
    AuthenticatedPgciIndexRoute: AuthenticatedPgciIndexRoute,
    AuthenticatedPgciAgreementsNewRoute: AuthenticatedPgciAgreementsNewRoute,
    AuthenticatedPgciAgreementsIndexRoute:
      AuthenticatedPgciAgreementsIndexRoute,
    AuthenticatedPgciAgreementsAgreementIdEditRoute:
      AuthenticatedPgciAgreementsAgreementIdEditRoute,
    AuthenticatedPgciAgreementsAgreementIdIndexRoute:
      AuthenticatedPgciAgreementsAgreementIdIndexRoute,
  }

const AuthenticatedPgciRouteRouteWithChildren =
  AuthenticatedPgciRouteRoute._addFileChildren(
    AuthenticatedPgciRouteRouteChildren,
  )

interface AuthenticatedSetupClientsClientIdRouteChildren {
  AuthenticatedSetupClientsClientIdCompaniesRoute: typeof AuthenticatedSetupClientsClientIdCompaniesRoute
  AuthenticatedSetupClientsClientIdEditRoute: typeof AuthenticatedSetupClientsClientIdEditRoute
  AuthenticatedSetupClientsClientIdIndexRoute: typeof AuthenticatedSetupClientsClientIdIndexRoute
}

const AuthenticatedSetupClientsClientIdRouteChildren: AuthenticatedSetupClientsClientIdRouteChildren =
  {
    AuthenticatedSetupClientsClientIdCompaniesRoute:
      AuthenticatedSetupClientsClientIdCompaniesRoute,
    AuthenticatedSetupClientsClientIdEditRoute:
      AuthenticatedSetupClientsClientIdEditRoute,
    AuthenticatedSetupClientsClientIdIndexRoute:
      AuthenticatedSetupClientsClientIdIndexRoute,
  }

const AuthenticatedSetupClientsClientIdRouteWithChildren =
  AuthenticatedSetupClientsClientIdRoute._addFileChildren(
    AuthenticatedSetupClientsClientIdRouteChildren,
  )

interface AuthenticatedSetupUsersUserIdRouteChildren {
  AuthenticatedSetupUsersUserIdClientAccessRoute: typeof AuthenticatedSetupUsersUserIdClientAccessRoute
  AuthenticatedSetupUsersUserIdEditRoute: typeof AuthenticatedSetupUsersUserIdEditRoute
  AuthenticatedSetupUsersUserIdIndexRoute: typeof AuthenticatedSetupUsersUserIdIndexRoute
}

const AuthenticatedSetupUsersUserIdRouteChildren: AuthenticatedSetupUsersUserIdRouteChildren =
  {
    AuthenticatedSetupUsersUserIdClientAccessRoute:
      AuthenticatedSetupUsersUserIdClientAccessRoute,
    AuthenticatedSetupUsersUserIdEditRoute:
      AuthenticatedSetupUsersUserIdEditRoute,
    AuthenticatedSetupUsersUserIdIndexRoute:
      AuthenticatedSetupUsersUserIdIndexRoute,
  }

const AuthenticatedSetupUsersUserIdRouteWithChildren =
  AuthenticatedSetupUsersUserIdRoute._addFileChildren(
    AuthenticatedSetupUsersUserIdRouteChildren,
  )

interface AuthenticatedSetupRouteRouteChildren {
  AuthenticatedSetupIndexRoute: typeof AuthenticatedSetupIndexRoute
  AuthenticatedSetupClientsClientIdRoute: typeof AuthenticatedSetupClientsClientIdRouteWithChildren
  AuthenticatedSetupClientsNewRoute: typeof AuthenticatedSetupClientsNewRoute
  AuthenticatedSetupProductsProductIdRoute: typeof AuthenticatedSetupProductsProductIdRoute
  AuthenticatedSetupProductsImportRoute: typeof AuthenticatedSetupProductsImportRoute
  AuthenticatedSetupUsersUserIdRoute: typeof AuthenticatedSetupUsersUserIdRouteWithChildren
  AuthenticatedSetupUsersNewRoute: typeof AuthenticatedSetupUsersNewRoute
  AuthenticatedSetupClientsIndexRoute: typeof AuthenticatedSetupClientsIndexRoute
  AuthenticatedSetupProductsIndexRoute: typeof AuthenticatedSetupProductsIndexRoute
  AuthenticatedSetupUsersIndexRoute: typeof AuthenticatedSetupUsersIndexRoute
}

const AuthenticatedSetupRouteRouteChildren: AuthenticatedSetupRouteRouteChildren =
  {
    AuthenticatedSetupIndexRoute: AuthenticatedSetupIndexRoute,
    AuthenticatedSetupClientsClientIdRoute:
      AuthenticatedSetupClientsClientIdRouteWithChildren,
    AuthenticatedSetupClientsNewRoute: AuthenticatedSetupClientsNewRoute,
    AuthenticatedSetupProductsProductIdRoute:
      AuthenticatedSetupProductsProductIdRoute,
    AuthenticatedSetupProductsImportRoute:
      AuthenticatedSetupProductsImportRoute,
    AuthenticatedSetupUsersUserIdRoute:
      AuthenticatedSetupUsersUserIdRouteWithChildren,
    AuthenticatedSetupUsersNewRoute: AuthenticatedSetupUsersNewRoute,
    AuthenticatedSetupClientsIndexRoute: AuthenticatedSetupClientsIndexRoute,
    AuthenticatedSetupProductsIndexRoute: AuthenticatedSetupProductsIndexRoute,
    AuthenticatedSetupUsersIndexRoute: AuthenticatedSetupUsersIndexRoute,
  }

const AuthenticatedSetupRouteRouteWithChildren =
  AuthenticatedSetupRouteRoute._addFileChildren(
    AuthenticatedSetupRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPgciRouteRoute: typeof AuthenticatedPgciRouteRouteWithChildren
  AuthenticatedSetupRouteRoute: typeof AuthenticatedSetupRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPgciRouteRoute: AuthenticatedPgciRouteRouteWithChildren,
  AuthenticatedSetupRouteRoute: AuthenticatedSetupRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
